name: RollingQuest
version: 1.0
main: me.ranol.rollingquest.RollingQuest
author: Ranol_
commands:
  rq:
    description: "RollingQuest's user command."
  rqa:
    description: "RollingQuest's admin command."
  questview:
    description: "opening the quest inventory."